apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-library
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.size }}
  {{- with .Values.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
